agent1.sources = s1
agent1.channels = c1
agent1.sinks = k1


agent1.sources.s1.type = http
agent1.sources.s1.bind = 0.0.0.0
agent1.sources.s1.port = 44444


agent1.channels.c1.type = memory
agent1.channels.c1.capacity = 10000


agent1.sinks.k1.type = org.apache.flume.sink.kafka.KafkaSink
agent1.sinks.k1.topic = stock_prices
agent1.sinks.k1.brokerList = localhost:9092


agent1.sources.s1.channels = c1
agent1.sinks.k1.channel = c1
