## Configuring Components
agent2.sources=source1
agent2.channels=channel1
agent2.sinks=sink1


## Configuring Source
agent2.sources.source1.type=org.apache.flume.source.kafka.KafkaSource
agent2.sources.source1.zookeeperConnect=localhost:2181
agent2.sources.source1.topic=stock_prices
agent2.sources.source1.groupId=flume
agent2.sources.source1.channels=channel1
agent2.sources.source1.interceptors=i1
agent2.sources.source1.interceptors.i1.type=timestamp
agent2.sources.source1.kafka.consumer.timeout.ms=100


## Configuring Channel
agent2.channels.channel1.type=memory
agent2.channels.channel1.capacity=10000
agent2.channels.channel1.transactionCapacity=1000

## Configuring sink
agent2.sinks.sink1.type=hdfs
agent2.sinks.sink1.channel=channel1
agent2.sinks.sink1.hdfs.path=/%{topic}/%y-%m-%d
## Number of seconds to wait before rolling current file
agent2.sinks.sink1.hdfs.rollInterval=5
## File size to trigger roll, in byte
agent2.sinks.sink1.hdfs.rollSize=1024
## Number of events written to file before it rolled
agent2.sinks.sink1.hdfs.rollCount=10
## DataStrem - Stores data instead of ASCII values of data
agent2.sinks.sink1.hdfs.fileType=DataStream
